### ISSUE TITLE
CustomDock motion not working 

### ISSUE THREAD

**Issue by Cassio7** [yatharth1706/personal-portfolio-v1#1]
Hi! I followed your youtube guide and i notice a bug on the CustomDock component.
When i load the page the animation (motion) is working, but if i scroll down, the animation starts to slowly not work anymore, become just static.

To fix this problem i changed `onMouseMove` function to this:
```typescript
onMouseMove={(e) => {
          if (orientation == "horizontal") {
            mouseX.set(e.clientX);
          } else {
            mouseY.set(e.clientY);
          }
        }}
```
Change `e.pageX` to `e.clientX` and also the Y. 

If you want i can open a pull request with the code, tnx for sharing this project!

**Comment by yatharth1706** [comment]
Nice, thanks buddy @Cassio7. I will fix this in my portfolio as well using your code. Thanks. 😊

**Comment by yatharth1706** [comment]
I just tested this. It works nice. Thanks for finding the fix for this. Appreciate it.
